## Numpy.array 的基本操作

In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性

In [4]:
x.ndim

1

In [5]:
X.ndim

2

In [6]:
x.shape

(10,)

In [7]:
X.shape

(3, 5)

In [8]:
x.size

10

In [9]:
X.size

15

In [10]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[0]

0

In [12]:
x[-1]

9

In [13]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
X[0][0] 

0

In [15]:
X[2, 2]

12

In [16]:
x[:5]

array([0, 1, 2, 3, 4])

In [17]:
x[5:]

array([5, 6, 7, 8, 9])

In [18]:
x[::2]

array([0, 2, 4, 6, 8])

In [19]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [22]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [26]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [27]:
X[0, :]

array([0, 1, 2, 3, 4])

In [28]:
X[0, :].ndim

1

In [29]:
X[:, 0]

array([ 0,  5, 10])

In [30]:
X[:, 0].ndim

1

In [31]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [32]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [33]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [35]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [37]:
subX = X[:2, :3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [38]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [39]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Reshape

In [41]:
x.shape

(10,)

In [42]:
x.ndim

1

In [46]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
B.ndim

2

In [51]:
B.shape

(1, 10)

In [52]:
x.shape

(10,)

In [53]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [54]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [55]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 合并操作

In [58]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

array([3, 2, 1])

In [59]:
x

array([1, 2, 3])

In [60]:
y

array([3, 2, 1])

In [62]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [63]:
z = np.array([666, 666, 666])

In [64]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [65]:
A = np.array([[1, 2 ,3],
             [4, 5, 6]])

In [66]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [79]:
 np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [81]:
np.concatenate([A, z], )

ValueError: all the input arrays must have same number of dimensions

In [82]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [83]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
A2 = np.concatenate([A, z.reshape(1, -1)])

In [85]:
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [86]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [88]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [89]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [90]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions

## 分隔操作

In [91]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
x1, x2, x3 = np.split(x, [3, 7])

In [94]:
x1

array([0, 1, 2])

In [95]:
x2

array([3, 4, 5, 6])

In [96]:
x3

array([7, 8, 9])

In [97]:
x1, x2 = np.split(x, [5])

In [98]:
x1

array([0, 1, 2, 3, 4])

In [99]:
x2

array([5, 6, 7, 8, 9])

In [100]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [102]:
A1, A2 = np.split(A, [2])

In [103]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [104]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
A1, A2 = np.split(A, [2], axis=1)

In [106]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [107]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [110]:
upper, lower = np.vsplit(A, [2])

In [111]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [112]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
left, right = np.hsplit(A, [2])

In [114]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [115]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [116]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
X, y = np.hsplit(data, [-1])

In [118]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [119]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [120]:
y[:, 0]

array([ 3,  7, 11, 15])