# 聚合运算

In [1]:
import numpy as np

L = np.random.random(100)

In [2]:
L

array([0.61621542, 0.82256012, 0.58247736, 0.12405049, 0.09903359,
       0.44597695, 0.6585146 , 0.86258332, 0.87743456, 0.7678999 ,
       0.23732104, 0.00292109, 0.35860756, 0.67641538, 0.62845178,
       0.71376334, 0.5420811 , 0.01708305, 0.97615735, 0.03425856,
       0.76115259, 0.18046626, 0.7277588 , 0.23730154, 0.0708445 ,
       0.94232809, 0.87242566, 0.48673683, 0.05946572, 0.87552711,
       0.96888037, 0.07412602, 0.20377662, 0.56445471, 0.50571164,
       0.59837353, 0.43928505, 0.99535611, 0.62680199, 0.89648053,
       0.6319767 , 0.84756281, 0.68980769, 0.04271503, 0.11597674,
       0.04871588, 0.13545129, 0.02677992, 0.30774585, 0.28171429,
       0.97885288, 0.51143824, 0.78923526, 0.93722076, 0.40542861,
       0.1249338 , 0.26906969, 0.46932041, 0.94011808, 0.2430496 ,
       0.65564557, 0.30714263, 0.97589627, 0.41781946, 0.67914668,
       0.32347802, 0.42300255, 0.19913701, 0.77448634, 0.45104865,
       0.8308918 , 0.94588619, 0.65262983, 0.92060706, 0.97649

In [3]:
sum(L)

53.0415340860796

In [4]:
np.sum(L)

53.04153408607962

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

98.1 ms ± 1.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
430 µs ± 15.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.min(big_array)

4.704617272421885e-07

In [7]:
np.max(big_array)

0.9999999502727718

In [8]:
big_array.max()

0.9999999502727718

In [9]:
big_array.min()

4.704617272421885e-07

In [10]:
big_array.sum()

500283.9663996866

In [11]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [14]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [15]:
np.prod(X)

0

In [16]:
np.prod(X + 1)

20922789888000

In [17]:
np.mean(X)

7.5

In [18]:
np.median(X)

7.5

In [19]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [20]:
np.median(v)

2.0

In [21]:
np.percentile(big_array, q=50)

0.5004622229191102

In [22]:
np.median(big_array)

0.5004622229191102

In [23]:
np.percentile(big_array, q=100)

0.9999999502727718

In [24]:
np.max(big_array)

0.9999999502727718

In [25]:
for precent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=precent))

4.704617272421885e-07
0.25053124175452535
0.5004622229191102
0.7499351851725748
0.9999999502727718


In [26]:
np.var(big_array)

0.08328936942938207

In [27]:
np.std(big_array)

0.28859897683356756

In [28]:
x = np.random.normal(0, 1, size=1000000)

In [29]:
np.mean(x)

-0.001978290656440633

In [30]:
np.std(x)

0.9984941335932416

## 索引

In [31]:
np.min(x)

-4.63009844484871

In [32]:
np.argmin(x)

549253

In [33]:
x[458326]

1.5208247372183183

In [34]:
np.argmax(x)

480776

In [35]:
x[113140]

-0.9862052982223343

In [36]:
np.max(x)

4.591835684339635

## 排序和使用索引

In [37]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
np.random.shuffle(x)
x

array([ 4,  7, 11,  3, 12,  0,  1, 14,  5,  8,  9,  6,  2, 13, 10, 15])

In [39]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
x

array([ 4,  7, 11,  3, 12,  0,  1, 14,  5,  8,  9,  6,  2, 13, 10, 15])

In [41]:
x.sort()

In [42]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
X = np.random.randint(10, size=(4, 4))
X

array([[9, 5, 5, 2],
       [5, 6, 2, 2],
       [9, 8, 0, 9],
       [9, 2, 9, 3]])

In [44]:
np.sort(X)

array([[2, 5, 5, 9],
       [2, 2, 5, 6],
       [0, 8, 9, 9],
       [2, 3, 9, 9]])

In [45]:
np.sort(X, axis=0)

array([[5, 2, 0, 2],
       [9, 5, 2, 2],
       [9, 6, 5, 3],
       [9, 8, 9, 9]])

In [47]:
np.random.shuffle(x)

In [48]:
x

array([ 2,  7,  8,  5, 11, 10,  6, 14,  4,  3,  9, 13, 12,  0, 15,  1])

In [49]:
np.argsort(x)

array([13, 15,  0,  9,  8,  3,  6,  1,  2, 10,  5,  4, 12, 11,  7, 14])

In [51]:
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  5,  6,  7, 10, 11,  9, 13, 12,  8, 15, 14])

In [52]:
np.argpartition(x, 3)

array([13, 15,  0,  9,  8,  3,  6,  1,  5,  4, 10, 11, 12,  2, 14,  7])

In [53]:
X

array([[9, 5, 5, 2],
       [5, 6, 2, 2],
       [9, 8, 0, 9],
       [9, 2, 9, 3]])

In [54]:
np.argsort(X, axis=1)

array([[3, 1, 2, 0],
       [2, 3, 0, 1],
       [2, 1, 0, 3],
       [1, 3, 0, 2]])

In [55]:
np.argsort(X, axis=0)

array([[1, 3, 2, 0],
       [0, 0, 1, 1],
       [2, 1, 0, 3],
       [3, 2, 3, 2]])

In [58]:
np.partition(X, 2, axis=1)

array([[2, 5, 5, 9],
       [2, 2, 5, 6],
       [0, 8, 9, 9],
       [2, 3, 9, 9]])

In [59]:
np.argpartition(X, 2, axis=1)

array([[3, 1, 2, 0],
       [2, 3, 0, 1],
       [2, 1, 0, 3],
       [1, 3, 2, 0]])

In [60]:
np.argpartition(X, 2, axis=0)

array([[1, 3, 2, 0],
       [0, 0, 1, 1],
       [2, 1, 0, 3],
       [3, 2, 3, 2]])

In [61]:
np.partition(X, 2, axis=0)

array([[5, 2, 0, 2],
       [9, 5, 2, 2],
       [9, 6, 5, 3],
       [9, 8, 9, 9]])