# 随机梯度下降法

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
m = 10000

x = np.random.normal(size = m)
X = x.reshape(-1, 1)
y = 4.*x + 3. + np.random.normal(0, 3, size=m)

In [3]:
history_theta = []
def J(theta, X_b, y):
    try:
        return np.sum((y - X_b.dot(theta)) ** 2.) / len(y)
    except:
        return float('inf')

def dJ(theta, X_b, y):
    return X_b.T.dot(X_b.dot(theta) - y) * 2. / len(y)

def gradient_descent(X_b, y, initial_theta, eta, n_iters=1e4, epsilon=1e-8):
    theta = initial_theta
    cur_iter = 0
    history_theta.append(theta)

    while cur_iter < n_iters:
        gradient = dJ(theta, X_b, y)
        last_theta = theta
        theta = theta - eta * gradient
        history_theta.append(theta)

        if(abs(J(theta, X_b, y) - J(last_theta, X_b, y)) < epsilon):
            break
        cur_iter += 1
    return theta

In [4]:
%%time
X_b = np.hstack([np.ones((len(X), 1)), X])
initial_theta = np.zeros(X_b.shape[1])
eta = 0.01

theta = gradient_descent(X_b, y, initial_theta, eta)

CPU times: user 109 ms, sys: 29 ms, total: 138 ms
Wall time: 107 ms


In [5]:
theta

array([3.01918081, 4.03207167])

In [6]:
history_theta

[array([0., 0.]),
 array([0.06057737, 0.08163455]),
 array([0.11993939, 0.16161648]),
 array([0.17811045, 0.23997924]),
 array([0.23511445, 0.31675562]),
 array([0.29097479, 0.39197773]),
 array([0.34571442, 0.46567703]),
 array([0.39935583, 0.53788435]),
 array([0.45192105, 0.60862989]),
 array([0.50343168, 0.67794326]),
 array([0.55390886, 0.74585343]),
 array([0.60337335, 0.81238881]),
 array([0.65184545, 0.87757724]),
 array([0.69934507, 0.94144599]),
 array([0.74589173, 1.00402176]),
 array([0.79150454, 1.06533074]),
 array([0.83620224, 1.12539857]),
 array([0.8800032 , 1.18425037]),
 array([0.92292539, 1.24191076]),
 array([0.96498646, 1.29840386]),
 array([1.00620368, 1.35375331]),
 array([1.04659398, 1.40798224]),
 array([1.08617395, 1.46111336]),
 array([1.12495985, 1.51316887]),
 array([1.16296761, 1.56417056]),
 array([1.20021283, 1.61413975]),
 array([1.23671083, 1.66309736]),
 array([1.27247659, 1.71106386]),
 array([1.30752481, 1.7580593 ]),
 array([1.34186987, 1.80410336

## 随机梯度下降法

In [7]:
def dJ_sgd(theta, X_b_i, y_i):
    return X_b_i.T.dot(X_b_i.dot(theta) - y_i) * 2.

In [8]:
history_theta = []
def sgd(X_b, y, initial_theta, n_iters):
    t0 = 5
    t1 = 50
    
    
    def learning_rate(t):
        return t0 / (t + t1)
    theta = initial_theta
    history_theta.append(theta)

    for cur_iter in range(n_iters):
        rand_i = np.random.randint(len(X_b))
        gradient = dJ_sgd(theta, X_b[rand_i], y[rand_i])
        theta = theta - learning_rate(cur_iter) * gradient
        history_theta.append(theta)

    return theta 

In [9]:
%%time
X_b = np.hstack([np.ones((len(X), 1)), X])
initial_theta = np.zeros(X_b.shape[1])

theta = sgd(X_b, y, initial_theta, n_iters=len(X_b)//3)

CPU times: user 31.2 ms, sys: 2.82 ms, total: 34 ms
Wall time: 31.9 ms


In [10]:
theta

array([3.29998084, 4.29777543])

In [11]:
history_theta

[array([0., 0.]),
 array([0.96827414, 1.60005162]),
 array([0.9270109 , 1.65299764]),
 array([-0.28146472,  2.49905125]),
 array([0.62707135, 3.09871178]),
 array([0.66876767, 3.11266777]),
 array([1.13147443, 3.49282879]),
 array([1.38883155, 3.50870866]),
 array([1.79245007, 3.63783792]),
 array([1.85609813, 3.7484571 ]),
 array([2.05671594, 3.57899029]),
 array([2.50895324, 3.85898013]),
 array([2.43375915, 3.97011817]),
 array([2.0127884 , 3.70761463]),
 array([2.23005389, 3.81078822]),
 array([2.31923407, 3.7517095 ]),
 array([2.55989247, 3.93966446]),
 array([1.93867994, 4.40494386]),
 array([2.06353436, 4.51949289]),
 array([1.94905488, 4.52383458]),
 array([1.27455967, 4.90573998]),
 array([1.31608089, 4.94968933]),
 array([1.77044713, 4.9676253 ]),
 array([1.76042383, 4.96132808]),
 array([1.57209492, 4.9128491 ]),
 array([1.86847096, 5.23984178]),
 array([1.43396116, 5.19451696]),
 array([1.90093687, 4.50174432]),
 array([2.13655373, 4.4469954 ]),
 array([3.25140424, 4.061838