# 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

## train_test_split

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
shuffle_indexes = np.random.permutation(len(X))

In [8]:
shuffle_indexes

array([108, 146, 123,  41,  71,  94, 126,  77, 139, 119,  86,  49,  66,
        59, 138, 125,  85, 100,  99, 133, 134, 107,  91,  48, 104,   4,
        58,  80,  69,  23,  62,  82,  44,  20, 132,   9,  98,  40,  74,
        25,   5,  67, 121,  76,  27,  88,   6,  64,  18,  42, 118,  12,
       140,  32, 109, 141, 110,  21,  45,  60,  55, 105,  51,   1,  97,
       144,  33,  13,  54,  84,  72,  83,  65,  81,  70,  22, 120,  75,
        34,   8,  92, 149, 136,  16, 142,  31,  30, 145, 124,  38,  47,
       122, 148,  39,  46,  63,   7, 129,  73, 128, 117, 130,  56, 103,
       135,  57, 143, 113, 111,  28,  36,   3, 112,  14, 137, 101,  15,
        35,   2, 115,  19,  53, 102, 116, 106,  10,  37,  95, 114,  43,
        79,  78,  11,  61,  17, 147,  26,  24,  52,   0,  90, 127,  50,
        96, 131,  93,  29,  87,  68,  89])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_size

30

In [11]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [12]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [13]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [14]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


## 使用我们的算法

In [15]:
from playML.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [17]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [18]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [19]:
from playML.kNN import KNNClassifier

In [20]:
my_knn_clf = KNNClassifier(k = 3)

In [21]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [22]:
y_predict = my_knn_clf.predict(X_test)

In [23]:
y_predict

array([2, 0, 1, 0, 2, 0, 2, 2, 1, 0, 1, 1, 1, 0, 2, 1, 2, 2, 2, 0, 0, 2,
       0, 2, 0, 1, 1, 2, 0, 2])

In [24]:
y_test

array([2, 0, 1, 0, 2, 0, 2, 2, 1, 0, 2, 1, 1, 0, 2, 1, 2, 2, 2, 0, 0, 2,
       0, 2, 0, 1, 1, 2, 0, 2])

In [25]:
sum(y_predict == y_test)

29

In [26]:
sum(y_predict == y_test)/len(y_test)

0.9666666666666667

## sklearn 中的 train_test_split

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [29]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [30]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
